// JV-1010 default patch list
// http://www.levente-zone.co.uk/Synths/JV1010_Ref_Manual/patch_list.htm

jvtool.userPatches = [
	{number: '001', name: 'Tremendously', voices: 4, poly: true},
	{number: '002', name: 'St.Concert', voices: 4, poly: true},
	{number: '003', name: 'CyberTrance2', voices: 4, poly: true},
	{number: '004', name: 'SessionNyln2', voices: 3, poly: true},
	{number: '005', name: 'ViennaStrgs3', voices: 4, poly: true},
	{number: '006', name: 'R&R Brass', voices: 3, poly: true},
	{number: '007', name: 'Velo Power', voices: 4, poly: true},
	{number: '008', name: 'Super Tenor', voices: 3, poly: true},
	{number: '009', name: 'Breathy Humz', voices: 2, poly: true},
	{number: '010', name: 'Ow Bass', voices: 1, poly: false},
	{number: '011', name: 'Dunes', voices: 4, poly: true},
	{number: '012', name: 'Celestial 2', voices: 4, poly: true},
	{number: '013', name: 'Tone Wh.Solo', voices: 3, poly: true},
	{number: '014', name: 'Poly Brs', voices: 4, poly: true},
	{number: '015', name: 'Combing Slow', voices: 3, poly: true},
	{number: '016', name: 'SA Rhodes 5', voices: 3, poly: true},
	{number: '017', name: 'Adrenaline', voices: 4, poly: true},
	{number: '018', name: 'DanceStack 1', voices: 3, poly: true},
	{number: '019', name: 'Flying Waltz', voices: 4, poly: true},
	{number: '020', name: 'East Europe', voices: 2, poly: true},
	{number: '021', name: 'Silky Way', voices: 2, poly: true},
	{number: '022', name: 'Techno Dream', voices: 3, poly: true},
	{number: '023', name: 'Raverborg', voices: 4, poly: true},
	{number: '024', name: 'Pan Pipes', voices: 2, poly: true},
	{number: '025', name: 'Pretty Bells', voices: 2, poly: true},
	{number: '026', name: 'Glistening', voices: 4, poly: true},
	{number: '027', name: 'Metal Solo', voices: 4, poly: true},
	{number: '028', name: 'StateXLChrd2', voices: 4, poly: false},
	{number: '029', name: 'Raggatronic', voices: 4, poly: true},
	{number: '030', name: 'ChristmasFlt', voices: 2, poly: true},
	{number: '031', name: 'Acc.de Paris', voices: 2, poly: true},
	{number: '032', name: 'DreamVoices2', voices: 2, poly: true},
	{number: '033', name: 'VintageCall2', voices: 4, poly: true},
	{number: '034', name: 'Trancing Pad', voices: 2, poly: true},
	{number: '035', name: 'OldiesOrgan2', voices: 2, poly: true},
	{number: '036', name: 'X..? Whistle', voices: 3, poly: true},
	{number: '037', name: 'Analog Drama', voices: 3, poly: true},
	{number: '038', name: 'BPF Lead', voices: 1, poly: true},
	{number: '039', name: 'Clean Tele', voices: 4, poly: true},
	{number: '040', name: 'Earth Blow', voices: 2, poly: true},
	{number: '041', name: 'Pulsatronic', voices: 3, poly: true},
	{number: '042', name: 'Funky Slap', voices: 1, poly: false},
	{number: '043', name: 'Echo Rhodes', voices: 4, poly: true},
	{number: '044', name: 'pp Harmonium', voices: 1, poly: true},
	{number: '045', name: 'Blue Notes', voices: 4, poly: true},
	{number: '046', name: 'Aurora', voices: 4, poly: true},
	{number: '047', name: 'Breathy Brs', voices: 3, poly: true},
	{number: '048', name: 'Enlighten', voices: 4, poly: true},
	{number: '049', name: 'Tube Smoke', voices: 2, poly: true},
	{number: '050', name: 'Perelandra', voices: 4, poly: true},
	{number: '051', name: 'SquareLead 2', voices: 2, poly: true},
	{number: '052', name: 'Shadows', voices: 4, poly: true},
	{number: '053', name: 'Organizer', voices: 3, poly: true},
	{number: '054', name: 'Full Orchest', voices: 4, poly: true},
	{number: '055', name: 'B\'on d\'moov!', voices: 3, poly: true},
	{number: '056', name: 'Sugar Bell 2', voices: 4, poly: true},
	{number: '057', name: 'Player\'s EP', voices: 2, poly: true},
	{number: '058', name: '4pole Bass', voices: 2, poly: false},
	{number: '059', name: 'Octapad', voices: 3, poly: true},
	{number: '060', name: 'Tria Bells', voices: 4, poly: true},
	{number: '061', name: 'Wire Pad', voices: 3, poly: true},
	{number: '062', name: 'Singing\'Mini', voices: 1, poly: false},
	{number: '063', name: 'Heirborne', voices: 4, poly: true},
	{number: '064', name: 'Trumpet', voices: 2, poly: true},
	{number: '065', name: 'Steel Away', voices: 3, poly: true},
	{number: '066', name: 'D-50 Stack', voices: 4, poly: true},
	{number: '067', name: 'Solo Strat', voices: 3, poly: true},
	{number: '068', name: 'Soap Opera', voices: 1, poly: true},
	{number: '069', name: 'Sop.Sax mf', voices: 2, poly: true},
	{number: '070', name: 'Dimensional', voices: 2, poly: true},
	{number: '071', name: 'Blusey OD', voices: 2, poly: true},
	{number: '072', name: 'Stacc.Heaven', voices: 4, poly: true},
	{number: '073', name: 'PhaseBlipper', voices: 2, poly: true},
	{number: '074', name: 'Pure Tibet', voices: 1, poly: true},
	{number: '075', name: 'Afterlife', voices: 3, poly: true},
	{number: '076', name: 'Perky B', voices: 2, poly: true},
	{number: '077', name: 'JUNO Power!', voices: 4, poly: true},
	{number: '078', name: 'SessionBrass', voices: 4, poly: true},
	{number: '079', name: 'JX SqrCarpet', voices: 2, poly: true},
	{number: '080', name: 'Phaser MC', voices: 2, poly: true},
	{number: '081', name: 'Sweep Clav 2', voices: 3, poly: true},
	{number: '082', name: 'BluesHarp', voices: 1, poly: true},
	{number: '083', name: 'Scat Flute', voices: 2, poly: true},
	{number: '084', name: '5thPad 2', voices: 4, poly: true},
	{number: '085', name: 'Belfry Chime', voices: 3, poly: true},
	{number: '086', name: 'Atmos Harp', voices: 4, poly: true},
	{number: '087', name: 'DesertCrystl', voices: 4, poly: true},
	{number: '088', name: 'December Sky', voices: 4, poly: true},
	{number: '089', name: 'Upright Pno', voices: 3, poly: true},
	{number: '090', name: 'Darkshine', voices: 4, poly: true},
	{number: '091', name: 'Exotic Velo', voices: 4, poly: true},
	{number: '092', name: 'Atlantis 2', voices: 4, poly: true},
	{number: '093', name: 'Creamy', voices: 2, poly: true},
	{number: '094', name: 'Morning Lite', voices: 2, poly: true},
	{number: '095', name: 'DanceStack 5', voices: 4, poly: true},
	{number: '096', name: 'D50FantaPerc', voices: 3, poly: true},
	{number: '097', name: 'Resojuice', voices: 2, poly: false},
	{number: '098', name: 'Silicon Str', voices: 4, poly: true},
	{number: '099', name: 'Keep :-)', voices: 2, poly: true},
	{number: '100', name: 'Sm.Brass Grp', voices: 4, poly: true},
	{number: '101', name: 'Echo Piano', voices: 3, poly: true},
	{number: '102', name: 'HeavenlyPad', voices: 2, poly: true},
	{number: '103', name: 'Sequalog', voices: 4, poly: true},
	{number: '104', name: 'Solo Steel', voices: 4, poly: true},
	{number: '105', name: 'Spectrum Mod', voices: 4, poly: true},
	{number: '106', name: 'Delicate EP', voices: 2, poly: true},
	{number: '107', name: 'Triumph Brs', voices: 3, poly: true},
	{number: '108', name: 'Flute ', voices: 1, poly: true},
	{number: '109', name: '2.2 Bell Pad', voices: 4, poly: true},
	{number: '110', name: 'JustLovely 2', voices: 1, poly: true},
	{number: '111', name: 'GR500 TmpDly', voices: 2, poly: true},
	{number: '112', name: 'Dawn 2 Dusk', voices: 3, poly: true},
	{number: '113', name: 'Gluey Pad', voices: 3, poly: true},
	{number: '114', name: 'SquareKeys 3', voices: 2, poly: true},
	{number: '115', name: 'Arasian Morn', voices: 4, poly: true},
	{number: '116', name: 'D\'light', voices: 2, poly: true},
	{number: '117', name: 'Perky Noize', voices: 3, poly: true},
	{number: '118', name: 'Mod DirtyWav', voices: 3, poly: true},
	{number: '119', name: 'Moving Glass', voices: 1, poly: true},
	{number: '120', name: 'Sci-Fi Str', voices: 3, poly: true},
	{number: '121', name: 'OD 5ths', voices: 3, poly: true},
	{number: '122', name: 'Far East', voices: 4, poly: true},
	{number: '123', name: 'Phobos', voices: 2, poly: true},
	{number: '124', name: 'Cyber Dreams', voices: 3, poly: true},
	{number: '125', name: 'Cave 2', voices: 4, poly: true},
	{number: '126', name: 'Helium Queen', voices: 4, poly: false},
	{number: '127', name: 'Rain Forest', voices: 4, poly: true},
	{number: '128', name: 'Crowds', voices: 4, poly: true}
];

jvtool.presetAPatches = [
	{number: '001', name: '64voicePiano', voices: 1, poly: true},
	{number: '002', name: 'Bright Piano', voices: 1, poly: true},
	{number: '003', name: 'Classique', voices: 2, poly: true},
	{number: '004', name: 'Nice Piano', voices: 3, poly: true},
	{number: '005', name: 'Piano Thang', voices: 3, poly: true},
	{number: '006', name: 'Power Grand', voices: 3, poly: true},
	{number: '007', name: 'House Piano', voices: 2, poly: true},
	{number: '008', name: 'E.Grand ', voices: 1, poly: true},
	{number: '009', name: 'MIDIed Grand', voices: 3, poly: true},
	{number: '010', name: 'Piano Blend', voices: 3, poly: true},
	{number: '011', name: 'West Coast', voices: 4, poly: true},
	{number: '012', name: 'PianoStrings', voices: 4, poly: true},
	{number: '013', name: 'Bs/Pno+Brs', voices: 4, poly: true},
	{number: '014', name: 'Waterhodes', voices: 2, poly: true},
	{number: '015', name: 'S.A.E.P. ', voices: 3, poly: true},
	{number: '016', name: 'SA Rhodes 1', voices: 4, poly: true},
	{number: '017', name: 'SA Rhodes 2', voices: 2, poly: true},
	{number: '018', name: 'Stiky Rhodes', voices: 3, poly: true},
	{number: '019', name: 'Dig Rhodes ', voices: 2, poly: true},
	{number: '020', name: 'Nylon EPiano ', voices: 4, poly: true},
	{number: '021', name: 'Nylon Rhodes', voices: 4, poly: true},
	{number: '022', name: 'Rhodes Mix ', voices: 3, poly: true},
	{number: '023', name: 'PsychoRhodes', voices: 2, poly: true},
	{number: '024', name: 'Tremo Rhodes', voices: 4, poly: true},
	{number: '025', name: 'MK-80 Rhodes', voices: 1, poly: true},
	{number: '026', name: 'MK-80 Phaser', voices: 1, poly: true},
	{number: '027', name: 'Delicate EP', voices: 2, poly: true},
	{number: '028', name: 'Octa Rhodes1', voices: 4, poly: true},
	{number: '029', name: 'Octa Rhodes2 ', voices: 4, poly: true},
	{number: '030', name: 'JV Rhodes+', voices: 4, poly: true},
	{number: '031', name: 'EP+Mod Pad ', voices: 4, poly: true},
	{number: '032', name: 'Mr.Mellow', voices: 4, poly: true},
	{number: '033', name: 'Comp Clav ', voices: 1, poly: true},
	{number: '034', name: 'Klavinet ', voices: 4, poly: true},
	{number: '035', name: 'Winger Clav', voices: 4, poly: true},
	{number: '036', name: 'Phaze Clav 1', voices: 2, poly: true},
	{number: '037', name: 'Phaze Clav 2', voices: 1, poly: true},
	{number: '038', name: 'Phuzz Clav ', voices: 2, poly: true},
	{number: '039', name: 'Chorus Clav', voices: 1, poly: true},
	{number: '040', name: 'Claviduck ', voices: 2, poly: true},
	{number: '041', name: 'Velo-Rez Clv ', voices: 1, poly: true},
	{number: '042', name: 'Clavicembalo', voices: 4, poly: true},
	{number: '043', name: 'Analog Clav1', voices: 1, poly: true},
	{number: '044', name: 'Analog Clav2 ', voices: 1, poly: true},
	{number: '045', name: 'Metal Clav ', voices: 3, poly: true},
	{number: '046', name: 'Full Stops ', voices: 2, poly: true},
	{number: '047', name: 'Ballad B ', voices: 3, poly: true},
	{number: '048', name: 'Mellow Bars', voices: 4, poly: true},
	{number: '049', name: 'AugerMentive', voices: 3, poly: true},
	{number: '050', name: 'Perky B ', voices: 2, poly: true},
	{number: '051', name: 'The Big Spin', voices: 3, poly: true},
	{number: '052', name: 'Gospel Spin', voices: 3, poly: true},
	{number: '053', name: 'Roller Spin', voices: 3, poly: true},
	{number: '054', name: 'Rocker Spin ', voices: 3, poly: true},
	{number: '055', name: 'Tone Wh.Solo', voices: 3, poly: true},
	{number: '056', name: 'Purple Spin ', voices: 4, poly: true},
	{number: '057', name: '60\'s LeadORG', voices: 2, poly: true},
	{number: '058', name: 'Assalt Organ', voices: 3, poly: true},
	{number: '059', name: 'D-50 Organ', voices: 2, poly: true},
	{number: '060', name: 'Cathedral', voices: 4, poly: true},
	{number: '061', name: 'Church Pipes', voices: 4, poly: true},
	{number: '062', name: 'Poly Key ', voices: 3, poly: true},
	{number: '063', name: 'Poly Saws ', voices: 4, poly: true},
	{number: '064', name: 'Poly Pulse', voices: 4, poly: true},
	{number: '065', name: 'Dual Profs', voices: 3, poly: true},
	{number: '066', name: 'Saw Mass ', voices: 4, poly: true},
	{number: '067', name: 'Poly Split ', voices: 4, poly: true},
	{number: '068', name: 'Poly Brass ', voices: 3, poly: true},
	{number: '069', name: 'Stackoid', voices: 4, poly: true},
	{number: '070', name: 'Poly Rock ', voices: 4, poly: true},
	{number: '071', name: 'D-50 Stack', voices: 4, poly: true},
	{number: '072', name: 'Fantasia JV', voices: 4, poly: true},
	{number: '073', name: 'Jimmee Dee', voices: 4, poly: true},
	{number: '074', name: 'Heavenals ', voices: 4, poly: true},
	{number: '075', name: 'Mallet Pad ', voices: 4, poly: true},
	{number: '076', name: 'Huff N Stuff', voices: 3, poly: true},
	{number: '077', name: 'Puff 1080', voices: 2, poly: true},
	{number: '078', name: 'BellVox 1080', voices: 4, poly: true},
	{number: '079', name: 'Fantasy Vox', voices: 4, poly: true},
	{number: '080', name: 'Square Keys', voices: 2, poly: true},
	{number: '081', name: 'Childlike ', voices: 4, poly: true},
	{number: '082', name: 'Music Box ', voices: 3, poly: true},
	{number: '083', name: 'Toy Box ', voices: 2, poly: true},
	{number: '084', name: 'Wave Bells ', voices: 4, poly: true},
	{number: '085', name: 'Tria Bells', voices: 4, poly: true},
	{number: '086', name: 'Beauty Bells', voices: 4, poly: true},
	{number: '087', name: 'Music Bells', voices: 2, poly: true},
	{number: '088', name: 'Pretty Bells', voices: 2, poly: true},
	{number: '089', name: 'Pulse Key', voices: 3, poly: true},
	{number: '090', name: 'Wide Tubular', voices: 4, poly: true},
	{number: '091', name: 'AmbienceVibe', voices: 4, poly: true},
	{number: '092', name: 'Warm Vibes', voices: 2, poly: true},
	{number: '093', name: 'Dyna Marimba', voices: 1, poly: true},
	{number: '094', name: 'Bass Marimba', voices: 4, poly: true},
	{number: '095', name: 'Nomad Perc ', voices: 3, poly: true},
	{number: '096', name: 'Ethno Metals ', voices: 4, poly: true},
	{number: '097', name: 'Islands Mlt', voices: 4, poly: true},
	{number: '098', name: 'Steelin Keys', voices: 3, poly: true},
	{number: '099', name: 'Steel Drums', voices: 1, poly: true},
	{number: '100', name: 'Voicey Pizz', voices: 3, poly: true},
	{number: '101', name: 'Sitar ', voices: 2, poly: true},
	{number: '102', name: 'Drone Split', voices: 4, poly: true},
	{number: '103', name: 'Ethnopluck', voices: 4, poly: true},
	{number: '104', name: 'Jamisen ', voices: 2, poly: true},
	{number: '105', name: 'Dulcimer', voices: 2, poly: true},
	{number: '106', name: 'East Melody', voices: 2, poly: true},
	{number: '107', name: 'MandolinTrem', voices: 4, poly: true},
	{number: '108', name: 'Nylon Gtr', voices: 1, poly: true},
	{number: '109', name: 'Gtr Strings ', voices: 3, poly: true},
	{number: '110', name: 'Steel Away', voices: 3, poly: true},
	{number: '111', name: 'Heavenly Gtr', voices: 4, poly: true},
	{number: '112', name: '12str Gtr 1', voices: 2, poly: true},
	{number: '113', name: '12str Gtr 2', voices: 3, poly: true},
	{number: '114', name: 'Jz Gtr Hall', voices: 1, poly: true},
	{number: '115', name: 'LetterFrmPat', voices: 4, poly: true},
	{number: '116', name: 'Jazz Scat', voices: 3, poly: true},
	{number: '117', name: 'Lounge Gig ', voices: 3, poly: true},
	{number: '118', name: 'JC Strat', voices: 1, poly: true},
	{number: '119', name: 'Twin Strats', voices: 3, poly: true},
	{number: '120', name: 'JV Strat', voices: 2, poly: true},
	{number: '121', name: 'Syn Strat ', voices: 2, poly: true},
	{number: '122', name: 'Rotary Gtr', voices: 2, poly: true},
	{number: '123', name: 'Muted Gtr', voices: 1, poly: true},
	{number: '124', name: 'SwitchOnMute', voices: 2, poly: true},
	{number: '125', name: 'Power Trip', voices: 2, poly: true},
	{number: '126', name: 'Crunch Split', voices: 4, poly: true},
	{number: '127', name: 'Rezodrive', voices: 2, poly: false},
	{number: '128', name: 'RockYurSocks', voices: 4, poly: false}
];

jvtool.presetBPatches = [
	{number: '001', name: 'Dist Gtr 1', voices: 3, poly: true},
	{number: '002', name: 'Dist Gtr 2', voices: 3, poly: true},
	{number: '003', name: 'R&R Chunk', voices: 4, poly: true},
	{number: '004', name: 'Phripphuzz', voices: 1, poly: false},
	{number: '005', name: 'Grungeroni', voices: 3, poly: true},
	{number: '006', name: 'Black Widow', voices: 4, poly: true},
	{number: '007', name: 'Velo-Wah Gtr', voices: 1, poly: true},
	{number: '008', name: 'Mod-Wah Gtr', voices: 2, poly: true},
	{number: '009', name: 'Pick Bass', voices: 1, poly: false},
	{number: '010', name: 'Hip Bass ', voices: 2, poly: true},
	{number: '011', name: 'Perc.Bass ', voices: 3, poly: false},
	{number: '012', name: 'Homey Bass ', voices: 2, poly: false},
	{number: '013', name: 'Finger Bass', voices: 1, poly: false},
	{number: '014', name: 'Nylon Bass', voices: 2, poly: true},
	{number: '015', name: 'Ac.Upright', voices: 1, poly: false},
	{number: '016', name: 'Wet Fretls', voices: 1, poly: false},
	{number: '017', name: 'Fretls Dry', voices: 2, poly: true},
	{number: '018', name: 'Slap Bass 1', voices: 2, poly: true},
	{number: '019', name: 'Slap Bass 2', voices: 1, poly: false},
	{number: '020', name: 'Slap Bass 3', voices: 1, poly: false},
	{number: '021', name: 'Slap Bass 4', voices: 2, poly: true},
	{number: '022', name: '4 Pole Bass ', voices: 1, poly: false},
	{number: '023', name: 'Tick Bass ', voices: 4, poly: false},
	{number: '024', name: 'House Bass', voices: 3, poly: false},
	{number: '025', name: 'Mondo Bass', voices: 3, poly: false},
	{number: '026', name: 'Clk AnalogBs', voices: 2, poly: false},
	{number: '027', name: 'Bass In Face', voices: 2, poly: true},
	{number: '028', name: '101 Bass ', voices: 2, poly: false},
	{number: '029', name: 'Noiz Bass ', voices: 2, poly: false},
	{number: '030', name: 'Super Jup Bs', voices: 2, poly: true},
	{number: '031', name: 'Occitan Bass', voices: 3, poly: true},
	{number: '032', name: 'Hugo Bass ', voices: 4, poly: false},
	{number: '033', name: 'Multi Bass', voices: 2, poly: true},
	{number: '034', name: 'Moist Bass', voices: 2, poly: false},
	{number: '035', name: 'BritelowBass', voices: 4, poly: false},
	{number: '036', name: 'Untamed Bass', voices: 3, poly: false},
	{number: '037', name: 'Rubber Bass', voices: 3, poly: false},
	{number: '038', name: 'Stereoww Bs', voices: 3, poly: false},
	{number: '039', name: 'Wonder Bass', voices: 3, poly: false},
	{number: '040', name: 'Deep Bass', voices: 2, poly: true},
	{number: '041', name: 'Super JX Bs', voices: 2, poly: false},
	{number: '042', name: 'W<RED>-Bass', voices: 4, poly: true},
	{number: '043', name: 'HI-Ring Bass', voices: 3, poly: true},
	{number: '044', name: 'Euro Bass', voices: 2, poly: false},
	{number: '045', name: 'SinusoidRave', voices: 1, poly: false},
	{number: '046', name: 'Alternative', voices: 2, poly: false},
	{number: '047', name: 'Acid Line', voices: 1, poly: false},
	{number: '048', name: 'Auto TB-303', voices: 3, poly: false},
	{number: '049', name: 'Hihat Tekno', voices: 2, poly: true},
	{number: '050', name: 'Velo Tekno 1', voices: 3, poly: false},
	{number: '051', name: 'Raggatronic', voices: 4, poly: true},
	{number: '052', name: 'Blade Racer', voices: 4, poly: true},
	{number: '053', name: 'S&H Pad ', voices: 1, poly: true},
	{number: '054', name: 'Syncrosonix', voices: 3, poly: true},
	{number: '055', name: 'Fooled Again ', voices: 1, poly: true},
	{number: '056', name: 'Alive ', voices: 3, poly: true},
	{number: '057', name: 'Velo Tekno 2', voices: 2, poly: true},
	{number: '058', name: 'Rezoid ', voices: 4, poly: true},
	{number: '059', name: 'Raverborg ', voices: 4, poly: true},
	{number: '060', name: 'Blow Hit', voices: 4, poly: true},
	{number: '061', name: 'Hammer Bell', voices: 3, poly: true},
	{number: '062', name: 'Seq Mallet', voices: 2, poly: true},
	{number: '063', name: 'Intentions ', voices: 3, poly: true},
	{number: '064', name: 'Pick It ', voices: 3, poly: true},
	{number: '065', name: 'Analog Seq', voices: 2, poly: true},
	{number: '066', name: 'Impact Vox ', voices: 4, poly: true},
	{number: '067', name: 'TeknoSoloVox ', voices: 2, poly: true},
	{number: '068', name: 'X-Mod Man', voices: 2, poly: true},
	{number: '069', name: 'Paz <==> Zap', voices: 1, poly: false},
	{number: '070', name: '4 Hits 4 You', voices: 4, poly: true},
	{number: '071', name: 'Impact', voices: 4, poly: true},
	{number: '072', name: 'Phase Hit', voices: 3, poly: true},
	{number: '073', name: 'Tekno Hit 1', voices: 2, poly: true},
	{number: '074', name: 'Tekno Hit 2', voices: 2, poly: true},
	{number: '075', name: 'Tekno Hit 3 ', voices: 4, poly: true},
	{number: '076', name: 'Reverse Hit', voices: 3, poly: true},
	{number: '077', name: 'SquareLead 1', voices: 3, poly: true},
	{number: '078', name: 'SquareLead 2', voices: 2, poly: true},
	{number: '079', name: 'You and Luck', voices: 2, poly: false},
	{number: '080', name: 'Belly Lead ', voices: 4, poly: true},
	{number: '081', name: 'WhistlinAtom ', voices: 2, poly: true},
	{number: '082', name: 'Edye Boost ', voices: 2, poly: false},
	{number: '083', name: 'MG Solo ', voices: 4, poly: false},
	{number: '084', name: 'FXM Saw Lead', voices: 4, poly: false},
	{number: '085', name: 'Sawteeth ', voices: 3, poly: false},
	{number: '086', name: 'Smoothe', voices: 2, poly: false},
	{number: '087', name: 'MG Lead', voices: 2, poly: false},
	{number: '088', name: 'MG Interval ', voices: 4, poly: false},
	{number: '089', name: 'Pulse Lead 1', voices: 3, poly: true},
	{number: '090', name: 'Pulse Lead 2', voices: 4, poly: false},
	{number: '091', name: 'Little Devil', voices: 4, poly: false},
	{number: '092', name: 'Loud SynLead', voices: 4, poly: false},
	{number: '093', name: 'Analog Lead', voices: 2, poly: false},
	{number: '094', name: '5th Lead', voices: 2, poly: false},
	{number: '095', name: 'Flute ', voices: 2, poly: true},
	{number: '096', name: 'Piccolo', voices: 1, poly: true},
	{number: '097', name: 'VOX Flute', voices: 4, poly: true},
	{number: '098', name: 'Air Lead ', voices: 2, poly: true},
	{number: '099', name: 'Pan Pipes', voices: 2, poly: true},
	{number: '100', name: 'Airplaaane', voices: 4, poly: true},
	{number: '101', name: 'Taj Mahal', voices: 1, poly: true},
	{number: '102', name: 'Raya Shaku', voices: 3, poly: true},
	{number: '103', name: 'Oboe mf ', voices: 1, poly: true},
	{number: '104', name: 'Oboe Express', voices: 2, poly: true},
	{number: '105', name: 'Clarinet mp', voices: 1, poly: true},
	{number: '106', name: 'ClariExpress', voices: 2, poly: true},
	{number: '107', name: 'Mitzva Split', voices: 4, poly: true},
	{number: '108', name: 'ChamberWinds', voices: 4, poly: true},
	{number: '109', name: 'ChamberWoods', voices: 3, poly: true},
	{number: '110', name: 'Film Orch ', voices: 4, poly: true},
	{number: '111', name: 'Sop.Sax mf', voices: 2, poly: true},
	{number: '112', name: 'Alto Sax', voices: 3, poly: true},
	{number: '113', name: 'AltoLead Sax', voices: 3, poly: true},
	{number: '114', name: 'Tenor Sax ', voices: 3, poly: true},
	{number: '115', name: 'Baritone Sax', voices: 3, poly: true},
	{number: '116', name: 'Take A Tenor', voices: 4, poly: true},
	{number: '117', name: 'Sax Section ', voices: 4, poly: true},
	{number: '118', name: 'Bigband Sax', voices: 4, poly: true},
	{number: '119', name: 'Harmonica', voices: 2, poly: true},
	{number: '120', name: 'Harmo Blues', voices: 2, poly: true},
	{number: '121', name: 'BluesHarp', voices: 1, poly: true},
	{number: '122', name: 'Hillbillys ', voices: 4, poly: true},
	{number: '123', name: 'French Bags ', voices: 4, poly: true},
	{number: '124', name: 'Majestic Tpt', voices: 1, poly: false},
	{number: '125', name: 'Voluntare ', voices: 2, poly: true},
	{number: '126', name: '2Trumpets ', voices: 2, poly: true},
	{number: '127', name: 'Tpt Sect ', voices: 4, poly: true},
	{number: '128', name: 'Mute TP mod ', voices: 4, poly: true}
];

jvtool.presetCPatches = [
	{number: '001', name: 'Harmon Mute', voices: 1, poly: true},
	{number: '002', name: 'Tp&Sax Sect', voices: 4, poly: true},
	{number: '003', name: 'Sax+Tp+Tb', voices: 3, poly: true},
	{number: '004', name: 'Brass Sect ', voices: 4, poly: true},
	{number: '005', name: 'Trombone', voices: 1, poly: true},
	{number: '006', name: 'Hybrid Bones', voices: 4, poly: true},
	{number: '007', name: 'Noble Horns', voices: 4, poly: true},
	{number: '008', name: 'Massed Horns', voices: 3, poly: true},
	{number: '009', name: 'Horn Swell', voices: 4, poly: true},
	{number: '010', name: 'Brass It! ', voices: 4, poly: true},
	{number: '011', name: 'Brass Attack', voices: 3, poly: true},
	{number: '012', name: 'Archimede ', voices: 3, poly: true},
	{number: '013', name: 'Rugby Horn', voices: 3, poly: true},
	{number: '014', name: 'MKS-80 Brass ', voices: 2, poly: true},
	{number: '015', name: 'True ANALOG', voices: 2, poly: true},
	{number: '016', name: 'Dark Vox', voices: 2, poly: true},
	{number: '017', name: 'RandomVowels', voices: 4, poly: true},
	{number: '018', name: 'Angels Sing', voices: 2, poly: true},
	{number: '019', name: 'Pvox Oooze', voices: 3, poly: true},
	{number: '020', name: 'Longing...', voices: 3, poly: true},
	{number: '021', name: 'Arasian Morn', voices: 4, poly: true},
	{number: '022', name: 'Beauty Vox', voices: 3, poly: true},
	{number: '023', name: 'Mary-AnneVox', voices: 4, poly: true},
	{number: '024', name: 'Belltree Vox', voices: 4, poly: true},
	{number: '025', name: 'Vox Panner', voices: 2, poly: true},
	{number: '026', name: 'Spaced Voxx', voices: 4, poly: true},
	{number: '027', name: 'Glass Voices', voices: 3, poly: true},
	{number: '028', name: 'Tubular Vox', voices: 4, poly: true},
	{number: '029', name: 'Velo Voxx', voices: 2, poly: true},
	{number: '030', name: 'Wavox', voices: 3, poly: true},
	{number: '031', name: 'Doos', voices: 1, poly: true},
	{number: '032', name: 'Synvox Comps', voices: 4, poly: true},
	{number: '033', name: 'Vocal Oohz', voices: 3, poly: true},
	{number: '034', name: 'LFO Vox', voices: 1, poly: true},
	{number: '035', name: 'St.Strings', voices: 2, poly: true},
	{number: '036', name: 'Warm Strings', voices: 4, poly: true},
	{number: '037', name: 'Somber Str', voices: 4, poly: true},
	{number: '038', name: 'Marcato', voices: 2, poly: true},
	{number: '039', name: 'Bright Str', voices: 2, poly: true},
	{number: '040', name: 'String Ens', voices: 4, poly: true},
	{number: '041', name: 'TremoloStrng', voices: 2, poly: true},
	{number: '042', name: 'Chambers', voices: 3, poly: true},
	{number: '043', name: 'ViolinCello', voices: 4, poly: true},
	{number: '044', name: 'Symphonique', voices: 4, poly: true},
	{number: '045', name: 'Film Octaves', voices: 4, poly: true},
	{number: '046', name: 'Film Layers', voices: 4, poly: true},
	{number: '047', name: 'Bass Pizz', voices: 4, poly: true},
	{number: '048', name: 'Real Pizz', voices: 3, poly: true},
	{number: '049', name: 'Harp On It', voices: 3, poly: true},
	{number: '050', name: 'Harp', voices: 2, poly: true},
	{number: '051', name: 'JP-8 Str 1', voices: 2, poly: true},
	{number: '052', name: 'JP-8 Str 2', voices: 3, poly: true},
	{number: '053', name: 'E-Motion Pad', voices: 4, poly: true},
	{number: '054', name: 'JP-8 Str 3', voices: 4, poly: true},
	{number: '055', name: 'Vintage Orch', voices: 4, poly: true},
	{number: '056', name: 'JUNO Strings', voices: 3, poly: true},
	{number: '057', name: 'Gigantalog', voices: 4, poly: true},
	{number: '058', name: 'PWM Strings', voices: 3, poly: true},
	{number: '059', name: 'Warmth', voices: 2, poly: true},
	{number: '060', name: 'ORBit Pad', voices: 2, poly: true},
	{number: '061', name: 'Deep Strings', voices: 2, poly: true},
	{number: '062', name: 'Pulsify', voices: 4, poly: true},
	{number: '063', name: 'Pulse Pad', voices: 4, poly: true},
	{number: '064', name: 'Greek Power', voices: 4, poly: true},
	{number: '065', name: 'Harmonicum', voices: 2, poly: true},
	{number: '066', name: 'D-50 Heaven', voices: 2, poly: true},
	{number: '067', name: 'Afro Horns', voices: 3, poly: true},
	{number: '068', name: 'Pop Pad', voices: 4, poly: true},
	{number: '069', name: 'Dreamesque', voices: 4, poly: true},
	{number: '070', name: 'Square Pad', voices: 4, poly: true},
	{number: '071', name: 'JP-8 Hollow', voices: 4, poly: true},
	{number: '072', name: 'JP-8Haunting', voices: 4, poly: true},
	{number: '073', name: 'Heirborne', voices: 4, poly: true},
	{number: '074', name: 'Hush Pad', voices: 4, poly: true},
	{number: '075', name: 'Jet Pad 1', voices: 2, poly: true},
	{number: '076', name: 'Jet Pad 2', voices: 2, poly: true},
	{number: '077', name: 'Phaze Pad', voices: 3, poly: true},
	{number: '078', name: 'Phaze Str', voices: 4, poly: true},
	{number: '079', name: 'Jet Str Ens', voices: 2, poly: true},
	{number: '080', name: 'Pivotal Pad', voices: 4, poly: true},
	{number: '081', name: '3D Flanged', voices: 1, poly: true},
	{number: '082', name: 'Fantawine', voices: 4, poly: true},
	{number: '083', name: 'Glassy Pad', voices: 3, poly: true},
	{number: '084', name: 'Moving Glass', voices: 1, poly: true},
	{number: '085', name: 'Glasswaves', voices: 3, poly: true},
	{number: '086', name: 'Shiny Pad', voices: 4, poly: true},
	{number: '087', name: 'ShiftedGlass', voices: 2, poly: true},
	{number: '088', name: 'Chime Pad', voices: 3, poly: true},
	{number: '089', name: 'Spin Pad', voices: 2, poly: true},
	{number: '090', name: 'Rotary Pad', voices: 4, poly: true},
	{number: '091', name: 'Dawn 2 Dusk', voices: 3, poly: true},
	{number: '092', name: 'Aurora ', voices: 4, poly: true},
	{number: '093', name: 'Strobe Mode', voices: 4, poly: true},
	{number: '094', name: 'Albion', voices: 2, poly: true},
	{number: '095', name: 'Running Pad', voices: 4, poly: true},
	{number: '096', name: 'Stepped Pad', voices: 4, poly: true},
	{number: '097', name: 'Random Pad', voices: 4, poly: true},
	{number: '098', name: 'SoundtrkDANC', voices: 4, poly: true},
	{number: '099', name: 'Flying Waltz', voices: 4, poly: true},
	{number: '100', name: 'Vanishing', voices: 1, poly: true},
	{number: '101', name: '5th Sweep', voices: 4, poly: true},
	{number: '102', name: 'Phazweep', voices: 4, poly: true},
	{number: '103', name: 'Big BPF', voices: 4, poly: true},
	{number: '104', name: 'MG Sweep', voices: 4, poly: true},
	{number: '105', name: 'CeremonyTimp', voices: 3, poly: true},
	{number: '106', name: 'Dyno Toms', voices: 4, poly: true},
	{number: '107', name: 'Sands ofTime', voices: 4, poly: true},
	{number: '108', name: 'Inertia', voices: 4, poly: true},
	{number: '109', name: 'Vektogram', voices: 4, poly: true},
	{number: '110', name: 'Crash Pad', voices: 4, poly: true},
	{number: '111', name: 'Feedback VOX', voices: 4, poly: true},
	{number: '112', name: 'Cascade', voices: 1, poly: true},
	{number: '113', name: 'Shattered', voices: 2, poly: true},
	{number: '114', name: 'NextFrontier', voices: 2, poly: true},
	{number: '115', name: 'Pure Tibet', voices: 1, poly: true},
	{number: '116', name: 'Chime Wash', voices: 4, poly: true},
	{number: '117', name: 'Night Shade', voices: 4, poly: true},
	{number: '118', name: 'Tortured', voices: 4, poly: true},
	{number: '119', name: 'Dissimilate', voices: 4, poly: true},
	{number: '120', name: 'Dunes', voices: 4, poly: true},
	{number: '121', name: 'Ocean Floor', voices: 1, poly: true},
	{number: '122', name: 'Cyber Space', voices: 3, poly: true},
	{number: '123', name: 'Biosphere', voices: 2, poly: true},
	{number: '124', name: 'Variable Run', voices: 4, poly: true},
	{number: '125', name: 'Ice Hall', voices: 2, poly: true},
	{number: '126', name: 'ComputerRoom', voices: 4, poly: true},
	{number: '127', name: 'Inverted', voices: 4, poly: true},
	{number: '128', name: 'Terminate', voices: 3, poly: true}
];

jvtool.presetDPatches = [
	{number: '001', name: 'Piano 1', voices: 2, poly: true},
	{number: '002', name: 'Piano 2', voices: 2, poly: true},
	{number: '003', name: 'Piano 3', voices: 2, poly: true},
	{number: '004', name: 'Honky-tonk', voices: 2, poly: true},
	{number: '005', name: 'E.Piano 1', voices: 2, poly: true},
	{number: '006', name: 'E.Piano 2', voices: 4, poly: true},
	{number: '007', name: 'Harpsichord', voices: 2, poly: true},
	{number: '008', name: 'Clav.', voices: 2, poly: true},
	{number: '009', name: 'Celesta', voices: 1, poly: true},
	{number: '010', name: 'Glockenspiel', voices: 2, poly: true},
	{number: '011', name: 'Music Box', voices: 1, poly: true},
	{number: '012', name: 'Vibraphone', voices: 1, poly: true},
	{number: '013', name: 'Marimba', voices: 2, poly: true},
	{number: '014', name: 'Xylophone', voices: 2, poly: true},
	{number: '015', name: 'Tubular-bell', voices: 2, poly: true},
	{number: '016', name: 'Santur', voices: 2, poly: true},
	{number: '017', name: 'Organ 1', voices: 1, poly: true},
	{number: '018', name: 'Organ 2', voices: 1, poly: true},
	{number: '019', name: 'Organ 3', voices: 2, poly: true},
	{number: '020', name: 'Church Org.1', voices: 2, poly: true},
	{number: '021', name: 'Reed Organ', voices: 1, poly: true},
	{number: '022', name: 'Accordion Fr', voices: 2, poly: true},
	{number: '023', name: 'Harmonica', voices: 1, poly: true},
	{number: '024', name: 'Bandoneon ', voices: 2, poly: true},
	{number: '025', name: 'Nylon-str.Gt', voices: 1, poly: true},
	{number: '026', name: 'Steel-str.Gt', voices: 1, poly: true},
	{number: '027', name: 'Jazz Gt. ', voices: 1, poly: true},
	{number: '028', name: 'Clean Gt. ', voices: 1, poly: true},
	{number: '029', name: 'Muted Gt.', voices: 1, poly: true},
	{number: '030', name: 'Overdrive Gt', voices: 1, poly: true},
	{number: '031', name: 'DistortionGt', voices: 1, poly: true},
	{number: '032', name: 'Gt.Harmonics', voices: 3, poly: true},
	{number: '033', name: 'Acoustic Bs.', voices: 3, poly: true},
	{number: '034', name: 'Fingered Bs.', voices: 1, poly: true},
	{number: '035', name: 'Picked Bs.', voices: 1, poly: true},
	{number: '036', name: 'Fretless Bs.', voices: 1, poly: true},
	{number: '037', name: 'Slap Bass 1', voices: 1, poly: true},
	{number: '038', name: 'Slap Bass 2', voices: 2, poly: true},
	{number: '039', name: 'Synth Bass 1', voices: 1, poly: true},
	{number: '040', name: 'Synth Bass 2', voices: 1, poly: true},
	{number: '041', name: 'Violin ', voices: 1, poly: true},
	{number: '042', name: 'Viola ', voices: 1, poly: true},
	{number: '043', name: 'Cello', voices: 1, poly: true},
	{number: '044', name: 'Contrabass', voices: 1, poly: true},
	{number: '045', name: 'Tremolo Str', voices: 1, poly: true},
	{number: '046', name: 'PizzicatoStr', voices: 1, poly: true},
	{number: '047', name: 'Harp', voices: 2, poly: true},
	{number: '048', name: 'Timpani', voices: 1, poly: true},
	{number: '049', name: 'Strings', voices: 2, poly: true},
	{number: '050', name: 'Slow Strings', voices: 1, poly: true},
	{number: '051', name: 'Syn.Strings1', voices: 2, poly: true},
	{number: '052', name: 'Syn.Strings2', voices: 2, poly: true},
	{number: '053', name: 'Choir Aahs', voices: 3, poly: true},
	{number: '054', name: 'Voice Oohs', voices: 1, poly: true},
	{number: '055', name: 'SynVox', voices: 1, poly: true},
	{number: '056', name: 'OrchestraHit', voices: 2, poly: true},
	{number: '057', name: 'Trumpet', voices: 2, poly: true},
	{number: '058', name: 'Trombone', voices: 1, poly: true},
	{number: '059', name: 'Tuba', voices: 2, poly: true},
	{number: '060', name: 'MutedTrumpet', voices: 1, poly: true},
	{number: '061', name: 'French Horn', voices: 2, poly: true},
	{number: '062', name: 'Brass 1', voices: 2, poly: true},
	{number: '063', name: 'Synth Brass1', voices: 1, poly: true},
	{number: '064', name: 'Synth Brass2', voices: 2, poly: true},
	{number: '065', name: 'Soprano Sax', voices: 1, poly: true},
	{number: '066', name: 'Alto Sax', voices: 1, poly: true},
	{number: '067', name: 'Tenor Sax', voices: 1, poly: true},
	{number: '068', name: 'Baritone Sax', voices: 2, poly: true},
	{number: '069', name: 'Oboe', voices: 2, poly: true},
	{number: '070', name: 'English Horn', voices: 2, poly: true},
	{number: '071', name: 'Bassoon', voices: 2, poly: true},
	{number: '072', name: 'Clarinet', voices: 1, poly: true},
	{number: '073', name: 'Piccolo', voices: 1, poly: true},
	{number: '074', name: 'Flute', voices: 1, poly: true},
	{number: '075', name: 'Recorder', voices: 2, poly: true},
	{number: '076', name: 'Pan Flute', voices: 2, poly: true},
	{number: '077', name: 'Bottle Blow', voices: 2, poly: true},
	{number: '078', name: 'Shakuhachi', voices: 1, poly: true},
	{number: '079', name: 'Whistle', voices: 1, poly: true},
	{number: '080', name: 'Ocarina', voices: 2, poly: true},
	{number: '081', name: 'Square Wave', voices: 2, poly: true},
	{number: '082', name: 'Saw Wave', voices: 2, poly: true},
	{number: '083', name: 'Syn.Calliope', voices: 2, poly: true},
	{number: '084', name: 'Chiffer Lead', voices: 2, poly: true},
	{number: '085', name: 'Charang', voices: 3, poly: true},
	{number: '086', name: 'Solo Vox', voices: 2, poly: true},
	{number: '087', name: '5th Saw Wave', voices: 3, poly: true},
	{number: '088', name: 'Bass & Lead', voices: 2, poly: true},
	{number: '089', name: 'Fantasia', voices: 3, poly: true},
	{number: '090', name: 'Warm Pad', voices: 2, poly: true},
	{number: '091', name: 'Polysynth', voices: 2, poly: true},
	{number: '092', name: 'Space Voice', voices: 2, poly: true},
	{number: '093', name: 'Bowed Glass', voices: 3, poly: true},
	{number: '094', name: 'Metal Pad', voices: 2, poly: true},
	{number: '095', name: 'Halo Pad', voices: 3, poly: true},
	{number: '096', name: 'Sweep Pad ', voices: 2, poly: true},
	{number: '097', name: 'Ice Rain', voices: 2, poly: true},
	{number: '098', name: 'Soundtrack', voices: 2, poly: true},
	{number: '099', name: 'Crystal', voices: 2, poly: true},
	{number: '100', name: 'Atmosphere', voices: 2, poly: true},
	{number: '101', name: 'Brightness', voices: 3, poly: true},
	{number: '102', name: 'Goblin', voices: 2, poly: true},
	{number: '103', name: 'Echo Drops ', voices: 2, poly: true},
	{number: '104', name: 'Star Theme ', voices: 2, poly: true},
	{number: '105', name: 'Sitar', voices: 1, poly: true},
	{number: '106', name: 'Banjo', voices: 1, poly: true},
	{number: '107', name: 'Shamisen', voices: 2, poly: true},
	{number: '108', name: 'Koto', voices: 1, poly: true},
	{number: '109', name: 'Kalimba', voices: 1, poly: true},
	{number: '110', name: 'Bag Pipe', voices: 3, poly: true},
	{number: '111', name: 'Fiddle', voices: 1, poly: true},
	{number: '112', name: 'Shanai', voices: 1, poly: true},
	{number: '113', name: 'Tinkle Bell', voices: 4, poly: true},
	{number: '114', name: 'Agogo', voices: 1, poly: true},
	{number: '115', name: 'Steel Drums', voices: 1, poly: true},
	{number: '116', name: 'Woodblock', voices: 1, poly: true},
	{number: '117', name: 'Taiko', voices: 4, poly: true},
	{number: '118', name: 'Melo. Tom 1', voices: 2, poly: true},
	{number: '119', name: 'Synth Drum', voices: 2, poly: true},
	{number: '120', name: 'Reverse Cym.', voices: 2, poly: true},
	{number: '121', name: 'Gt.FretNoise', voices: 1, poly: true},
	{number: '122', name: 'Breath Noise', voices: 2, poly: true},
	{number: '123', name: 'Seashore', voices: 3, poly: true},
	{number: '124', name: 'Bird', voices: 4, poly: true},
	{number: '125', name: 'Telephone 1', voices: 1, poly: true},
	{number: '126', name: 'Helicopter', voices: 2, poly: true},
	{number: '127', name: 'Applause', voices: 4, poly: true},
	{number: '128', name: 'Gun Shot', voices: 2, poly: true}
];

jvtool.presetEPatches = [
	{number: '001', name: 'Echo Piano', voices: 3, poly: true},
	{number: '002', name: 'Upright Pno ', voices: 3, poly: true},
	{number: '003', name: 'RD-1000', voices: 3, poly: true},
	{number: '004', name: 'Player\'s EP ', voices: 2, poly: true},
	{number: '005', name: 'D-50 Rhodes ', voices: 4, poly: true},
	{number: '006', name: 'Innocent EP ', voices: 2, poly: true},
	{number: '007', name: 'Echo Rhodes ', voices: 4, poly: true},
	{number: '008', name: 'See-Thru EP ', voices: 3, poly: true},
	{number: '009', name: 'FM BellPiano', voices: 3, poly: true},
	{number: '010', name: 'Ring E.Piano', voices: 4, poly: true},
	{number: '011', name: 'Soap Opera', voices: 1, poly: true},
	{number: '012', name: 'Dirty Organ ', voices: 3, poly: true},
	{number: '013', name: 'Surf\'s Up!', voices: 2, poly: true},
	{number: '014', name: 'Organesque', voices: 3, poly: true},
	{number: '015', name: 'pp Harmonium', voices: 1, poly: true},
	{number: '016', name: 'PieceOfCheez', voices: 1, poly: true},
	{number: '017', name: 'Harpsy Clav ', voices: 2, poly: true},
	{number: '018', name: 'Exotic Velo ', voices: 4, poly: true},
	{number: '019', name: 'HolidayCheer', voices: 4, poly: true},
	{number: '020', name: 'Morning Lite', voices: 2, poly: true},
	{number: '021', name: 'Prefab Chime', voices: 3, poly: true},
	{number: '022', name: 'Belfry Chime', voices: 3, poly: true},
	{number: '023', name: 'Stacc.Heaven', voices: 4, poly: true},
	{number: '024', name: '2.2 Bell Pad', voices: 4, poly: true},
	{number: '025', name: 'Far East', voices: 4, poly: true},
	{number: '026', name: 'Wire Pad', voices: 3, poly: true},
	{number: '027', name: 'PhaseBlipper', voices: 2, poly: true},
	{number: '028', name: 'Sweep Clav', voices: 3, poly: true},
	{number: '029', name: 'Glider', voices: 2, poly: true},
	{number: '030', name: 'Solo Steel', voices: 4, poly: true},
	{number: '031', name: 'DesertCrystl', voices: 4, poly: true},
	{number: '032', name: 'Clear Guitar', voices: 3, poly: true},
	{number: '033', name: 'Solo Strat', voices: 3, poly: true},
	{number: '034', name: 'Feed Me!', voices: 4, poly: true},
	{number: '035', name: 'Tube Smoke', voices: 2, poly: true},
	{number: '036', name: 'Creamy', voices: 2, poly: true},
	{number: '037', name: 'Blusey OD', voices: 2, poly: true},
	{number: '038', name: 'Grindstone', voices: 2, poly: true},
	{number: '039', name: 'OD 5ths', voices: 3, poly: true},
	{number: '040', name: 'East Europe ', voices: 2, poly: true},
	{number: '041', name: 'Dulcitar', voices: 4, poly: true},
	{number: '042', name: 'Atmos Harp', voices: 4, poly: true},
	{number: '043', name: 'Pilgrimage', voices: 4, poly: true},
	{number: '044', name: '202 Rude Bs ', voices: 2, poly: false},
	{number: '045', name: '2pole Bass', voices: 2, poly: false},
	{number: '046', name: '4pole Bass', voices: 2, poly: false},
	{number: '047', name: 'Phaser MC', voices: 2, poly: true},
	{number: '048', name: 'Miniphaser', voices: 2, poly: true},
	{number: '049', name: 'Acid TB', voices: 1, poly: false},
	{number: '050', name: 'Full Orchest', voices: 4, poly: true},
	{number: '051', name: 'Str + Winds ', voices: 4, poly: true},
	{number: '052', name: 'Flute 2080', voices: 2, poly: true},
	{number: '053', name: 'Scat Flute', voices: 2, poly: true},
	{number: '054', name: 'Sax Choir', voices: 4, poly: true},
	{number: '055', name: 'Ballad Trump', voices: 4, poly: true},
	{number: '056', name: 'Sm.Brass Grp', voices: 4, poly: true},
	{number: '057', name: 'Royale', voices: 4, poly: true},
	{number: '058', name: 'Brass Mutes ', voices: 2, poly: true},
	{number: '059', name: 'Breathy Brs ', voices: 3, poly: true},
	{number: '060', name: '3 Osc Brass ', voices: 3, poly: true},
	{number: '061', name: 'P5 Polymod', voices: 2, poly: true},
	{number: '062', name: 'Triumph Brs ', voices: 3, poly: true},
	{number: '063', name: 'Techno Dream', voices: 3, poly: true},
	{number: '064', name: 'Organizer', voices: 3, poly: true},
	{number: '065', name: 'Civilization', voices: 3, poly: true},
	{number: '066', name: 'Mental Chord', voices: 4, poly: false},
	{number: '067', name: 'House Chord ', voices: 4, poly: false},
	{number: '068', name: 'Sequalog', voices: 4, poly: true},
	{number: '069', name: 'Booster Bips', voices: 2, poly: true},
	{number: '070', name: 'VintagePlunk', voices: 4, poly: false},
	{number: '071', name: 'Plik-Plok', voices: 2, poly: true},
	{number: '072', name: 'RingSequence', voices: 4, poly: true},
	{number: '073', name: 'Cyber Swing', voices: 4, poly: true},
	{number: '074', name: 'Keep :-)', voices: 2, poly: true},
	{number: '075', name: 'Resojuice', voices: 2, poly: false},
	{number: '076', name: 'B\'on d\'moov!', voices: 3, poly: true},
	{number: '077', name: 'Dist TB-303 ', voices: 2, poly: false},
	{number: '078', name: 'Temple of JV', voices: 4, poly: true},
	{number: '079', name: 'Planet Asia ', voices: 4, poly: true},
	{number: '080', name: 'Afterlife', voices: 3, poly: true},
	{number: '081', name: 'Trancing Pad', voices: 2, poly: true},
	{number: '082', name: 'Pulsatronic ', voices: 3, poly: true},
	{number: '083', name: 'Cyber Dreams', voices: 3, poly: true},
	{number: '084', name: 'Warm Pipe', voices: 1, poly: false},
	{number: '085', name: 'Pure Pipe', voices: 2, poly: true},
	{number: '086', name: 'SH-2000', voices: 2, poly: false},
	{number: '087', name: 'X..? Whistle', voices: 3, poly: true},
	{number: '088', name: 'Jay Vee Solo', voices: 3, poly: true},
	{number: '089', name: 'Progresso Ld', voices: 4, poly: false},
	{number: '090', name: 'Adrenaline', voices: 4, poly: true},
	{number: '091', name: 'Enlighten', voices: 4, poly: true},
	{number: '092', name: 'Glass Blower', voices: 3, poly: true},
	{number: '093', name: 'Earth Blow', voices: 2, poly: true},
	{number: '094', name: 'JX SqrCarpet', voices: 2, poly: true},
	{number: '095', name: 'Dimensional ', voices: 2, poly: true},
	{number: '096', name: 'Jupiterings ', voices: 2, poly: true},
	{number: '097', name: 'Analog Drama', voices: 3, poly: true},
	{number: '098', name: 'Rich Dynapad', voices: 4, poly: true},
	{number: '099', name: 'Silky Way', voices: 2, poly: true},
	{number: '100', name: 'Gluey Pad', voices: 3, poly: true},
	{number: '101', name: 'BandPass Mod', voices: 2, poly: true},
	{number: '102', name: 'Soundtraque ', voices: 2, poly: true},
	{number: '103', name: 'Translucence', voices: 4, poly: true},
	{number: '104', name: 'Darkshine', voices: 4, poly: true},
	{number: '105', name: 'D\'light', voices: 2, poly: true},
	{number: '106', name: 'December Sky', voices: 4, poly: true},
	{number: '107', name: 'Octapad', voices: 3, poly: true},
	{number: '108', name: 'JUNO Power! ', voices: 4, poly: true},
	{number: '109', name: 'Spectrum Mod', voices: 4, poly: true},
	{number: '110', name: 'Stringsheen ', voices: 3, poly: true},
	{number: '111', name: 'GR500 TmpDly', voices: 2, poly: true},
	{number: '112', name: 'Mod DirtyWav', voices: 3, poly: true},
	{number: '113', name: 'Silicon Str ', voices: 4, poly: true},
	{number: '114', name: 'D50FantaPerc', voices: 3, poly: true},
	{number: '115', name: 'Rotodreams', voices: 3, poly: true},
	{number: '116', name: 'Blue Notes', voices: 4, poly: true},
	{number: '117', name: 'RiversOfTime', voices: 4, poly: true},
	{number: '118', name: 'Phobos', voices: 2, poly: true},
	{number: '119', name: '2 0 8 0', voices: 4, poly: true},
	{number: '120', name: 'Unearthly', voices: 4, poly: true},
	{number: '121', name: 'Glistening', voices: 4, poly: true},
	{number: '122', name: 'Sci-Fi Str', voices: 3, poly: true},
	{number: '123', name: 'Shadows', voices: 4, poly: true},
	{number: '124', name: 'Helium Queen', voices: 4, poly: false},
	{number: '125', name: 'Sci-Fi FX x4', voices: 1, poly: true},
	{number: '126', name: 'Perky Noize ', voices: 3, poly: true},
	{number: '127', name: 'Droplet', voices: 3, poly: true},
	{number: '128', name: 'Rain Forest ', voices: 4, poly: true}
];

jvtool.sessionPatches = [
	{number: '001', name: 'St.Concert', voices: 4},
	{number: '002', name: '9ft.Grand 1', voices: 4},
	{number: '003', name: '9ft.Grand 2', voices: 4},
	{number: '004', name: 'Euro Classic', voices: 2},
	{number: '005', name: 'St.Pno & Str', voices: 4},
	{number: '006', name: 'Compress Pno', voices: 1},
	{number: '007', name: 'LA Session', voices: 4},
	{number: '008', name: 'Water Piano', voices: 4},
	{number: '009', name: 'Vibra Rhodes', voices: 3},
	{number: '010', name: 'Stack Rhodes', voices: 4},
	{number: '011', name: 'ArcoEnsemble', voices: 2},
	{number: '012', name: 'Vienna Strgs', voices: 3},
	{number: '013', name: 'Str Adagio', voices: 2},
	{number: '014', name: 'Oct Strings', voices: 3},
	{number: '015', name: 'Silky Filter', voices: 2},
	{number: '016', name: 'Soft Strings', voices: 2},
	{number: '017', name: 'SlowStr.Sect', voices: 2},
	{number: '018', name: 'GiantStrings', voices: 4},
	{number: '019', name: 'Str+Choir 1', voices: 4},
	{number: '020', name: 'Str+Choir 2', voices: 4},
	{number: '021', name: 'Str+Choir 3', voices: 4},
	{number: '022', name: 'Breathy Humz', voices: 2},
	{number: '023', name: 'Dream Voices', voices: 2},
	{number: '024', name: 'Mmmms', voices: 2},
	{number: '025', name: 'Chorale', voices: 1},
	{number: '026', name: 'Space Men', voices: 3},
	{number: '027', name: 'Choir Mm+Aah', voices: 4},
	{number: '028', name: 'Ivory Mist', voices: 4},
	{number: '029', name: 'PercussiVox', voices: 4},
	{number: '030', name: 'Mysteriouso', voices: 3},
	{number: '031', name: 'Phase Mmhs', voices: 3},
	{number: '032', name: 'AmbientStory', voices: 4},
	{number: '033', name: 'Venus', voices: 3},
	{number: '034', name: 'SessionBrass', voices: 4},
	{number: '035', name: 'Port.Tpts', voices: 2},
	{number: '036', name: 'R&R Brass', voices: 3},
	{number: '037', name: 'Echo Brass', voices: 4},
	{number: '038', name: 'E.Coast Brs', voices: 4},
	{number: '039', name: 'Bop Soli', voices: 2},
	{number: '040', name: 'Soft Saxes', voices: 4},
	{number: '041', name: 'Orchestral', voices: 4},
	{number: '042', name: 'Octalog Hrn', voices: 2},
	{number: '043', name: 'Tpt Soloist', voices: 1},
	{number: '044', name: 'Legato Tpt', voices: 2},
	{number: '045', name: 'Dyno Trumpet', voices: 2},
	{number: '046', name: 'Ethno-Trumps', voices: 2},
	{number: '047', name: 'Super Tenor', voices: 3},
	{number: '048', name: 'TenorExpress', voices: 2},
	{number: '049', name: 'T.Sax f', voices: 1},
	{number: '050', name: 'Legato Flute', voices: 2},
	{number: '051', name: 'Touch Flute', voices: 2},
	{number: '052', name: 'NewAge Flute', voices: 1},
	{number: '053', name: 'Flute inMist', voices: 2},
	{number: '054', name: 'Hybrid Flute', voices: 2},
	{number: '055', name: 'Flute & Cla', voices: 3},
	{number: '056', name: 'ChristmasFlt', voices: 2},
	{number: '057', name: 'Fifth Flute', voices: 2},
	{number: '058', name: 'Cosmic Flute', voices: 2},
	{number: '059', name: 'Acc.de Paris', voices: 2},
	{number: '060', name: 'Paris 50\'s', voices: 4},
	{number: '061', name: 'Musette Ens', voices: 4},
	{number: '062', name: 'Montmartre', voices: 2},
	{number: '063', name: 'Sad Akordion', voices: 3},
	{number: '064', name: 'Fr.Accordion', voices: 1},
	{number: '065', name: 'Fr.Accord 2', voices: 2},
	{number: '066', name: 'Troubadour', voices: 3},
	{number: '067', name: 'SessionNylon', voices: 3},
	{number: '068', name: 'Solo Nylon 1', voices: 3},
	{number: '069', name: 'Solo Nylon 2', voices: 2},
	{number: '070', name: 'Nylon & Str', voices: 4},
	{number: '071', name: 'Nylon & Flt', voices: 3},
	{number: '072', name: 'Nylon Chord', voices: 3},
	{number: '073', name: 'Stratar', voices: 2},
	{number: '074', name: 'Clean Tele', voices: 4},
	{number: '075', name: 'Nashville', voices: 1},
	{number: '076', name: 'Super Trem', voices: 4},
	{number: '077', name: 'SpaghettiGtr', voices: 2},
	{number: '078', name: 'Duanne\'sTone', voices: 2},
	{number: '079', name: 'Big Hair Ld', voices: 2},
	{number: '080', name: 'Metal Solo', voices: 4},
	{number: '081', name: 'Crunch Tone', voices: 1},
	{number: '082', name: 'Overdriven', voices: 1},
	{number: '083', name: 'Blues Tele', voices: 4},
	{number: '084', name: 'Tube Double', voices: 2},
	{number: '085', name: 'Neil\'s Rust', voices: 4},
	{number: '086', name: 'Short Crunch', voices: 4},
	{number: '087', name: 'X-Fade Metal', voices: 4},
	{number: '088', name: 'Velo Power', voices: 4},
	{number: '089', name: 'Phazy Chunk', voices: 4},
	{number: '090', name: 'Reso Tele', voices: 1},
	{number: '091', name: 'Wah Wah BPM', voices: 4},
	{number: '092', name: 'Rock P.Bass1', voices: 1},
	{number: '093', name: 'Rock P.Bass2', voices: 2},
	{number: '094', name: 'Rock P.Bass3', voices: 4},
	{number: '095', name: 'Big Jazz Bs', voices: 3},
	{number: '096', name: 'BriteJazz Bs', voices: 1},
	{number: '097', name: 'Ch.Jazz Bs', voices: 2},
	{number: '098', name: 'Mellow Jz Bs', voices: 2},
	{number: '099', name: 'Mute E.Bs', voices: 1},
	{number: '100', name: 'Octabahn Bs', voices: 4},
	{number: '101', name: 'Slobbery Bs', voices: 2},
	{number: '102', name: 'Phase Worm', voices: 2},
	{number: '103', name: 'Euro Rave Bs', voices: 2},
	{number: '104', name: 'Pumpin\' Bs', voices: 3},
	{number: '105', name: 'Tech NoBase', voices: 2},
	{number: '106', name: 'Bad Acid Bs', voices: 2},
	{number: '107', name: 'CheepEcho Bs', voices: 3},
	{number: '108', name: 'Manic Bs', voices: 4},
	{number: '109', name: 'JP6 Sqr Key', voices: 2},
	{number: '110', name: 'Square drops', voices: 1},
	{number: '111', name: 'Celestial', voices: 3},
	{number: '112', name: 'Heavenly Eko', voices: 4},
	{number: '113', name: 'JD-800 Nomad', voices: 3},
	{number: '114', name: 'Vibrolater', voices: 4},
	{number: '115', name: 'MartianChime', voices: 4},
	{number: '116', name: 'Big Wet Blip', voices: 4},
	{number: '117', name: 'Amazing Echo', voices: 4},
	{number: '118', name: 'DelaySession', voices: 4},
	{number: '119', name: 'Deletex', voices: 4},
	{number: '120', name: 'Tarlia', voices: 3},
	{number: '121', name: 'Mahoroba', voices: 4},
	{number: '122', name: 'Eurotek Clav', voices: 2},
	{number: '123', name: 'Dope Resoclv', voices: 1},
	{number: '124', name: 'Tekno Juno', voices: 2},
	{number: '125', name: 'Buzzzzzzzzzz', voices: 2},
	{number: '126', name: 'Slop-a-rama', voices: 2},
	{number: '127', name: 'Isn\'t Pretty', voices: 3},
	{number: '128', name: 'Polywasp', voices: 1},
	{number: '129', name: 'Quixelate', voices: 4},
	{number: '130', name: 'Trangoa Wave', voices: 2},
	{number: '131', name: 'Spiked Cheez', voices: 3},
	{number: '132', name: 'Glassy Cheez', voices: 3},
	{number: '133', name: 'Super 808Cow', voices: 4},
	{number: '134', name: 'Arpeggiatoid', voices: 4},
	{number: '135', name: 'Euro Hit 1', voices: 4},
	{number: '136', name: 'Euro Hit 2', voices: 2},
	{number: '137', name: 'Rave Slice', voices: 1},
	{number: '138', name: 'Str Torture', voices: 2},
	{number: '139', name: 'Juno Harpsi', voices: 3},
	{number: '140', name: 'Big Mess Pad', voices: 4},
	{number: '141', name: 'Harpsichoir', voices: 4},
	{number: '142', name: 'Echo Juno', voices: 3},
	{number: '143', name: 'Phazerave', voices: 2},
	{number: '144', name: 'DanceStack 1', voices: 3},
	{number: '145', name: 'DanceStack 2', voices: 4},
	{number: '146', name: 'DanceStack 3', voices: 4},
	{number: '147', name: 'DanceStack 4', voices: 3},
	{number: '148', name: 'DanceStack 5', voices: 4},
	{number: '149', name: 'DanceStack 6', voices: 3},
	{number: '150', name: 'DanceStack 7', voices: 4},
	{number: '151', name: 'DanceStack 8', voices: 4},
	{number: '152', name: 'Eurotek Brs', voices: 4},
	{number: '153', name: 'Synergy Brs', voices: 4},
	{number: '154', name: 'PortaSynthex', voices: 3},
	{number: '155', name: 'Razor VCOs', voices: 4},
	{number: '156', name: 'Big PWM', voices: 2},
	{number: '157', name: 'Flutey Stack', voices: 2},
	{number: '158', name: 'Wobbly 5th', voices: 4},
	{number: '159', name: 'Tekno Square', voices: 3},
	{number: '160', name: 'Trance VoXxX', voices: 4},
	{number: '161', name: 'Random Rave', voices: 3},
	{number: '162', name: 'Raver Circus', voices: 4},
	{number: '163', name: 'Resorave', voices: 2},
	{number: '164', name: 'Flangomatic', voices: 2},
	{number: '165', name: 'O-Zu-Nu', voices: 4},
	{number: '166', name: 'Sub Divided', voices: 1},
	{number: '167', name: 'Ancient Sqr', voices: 2},
	{number: '168', name: 'Fat Flange', voices: 2},
	{number: '169', name: 'Phaze NRG', voices: 1},
	{number: '170', name: 'Phase Vox', voices: 3},
	{number: '171', name: 'Systekno', voices: 4},
	{number: '172', name: 'On the move!', voices: 2},
	{number: '173', name: 'XP\'ration', voices: 2},
	{number: '174', name: 'Big Ensemble', voices: 4},
	{number: '175', name: 'Lazerette', voices: 3},
	{number: '176', name: 'Fazed String', voices: 4},
	{number: '177', name: 'Combing Slow', voices: 3},
	{number: '178', name: 'Jet Stack', voices: 4},
	{number: '179', name: 'Phazeslopad', voices: 4},
	{number: '180', name: 'Rize Mass', voices: 3},
	{number: '181', name: 'Portent', voices: 2},
	{number: '182', name: 'DCO Sweeper', voices: 3},
	{number: '183', name: 'Sweep Rain', voices: 4},
	{number: '184', name: 'Sweep Stack', voices: 3},
	{number: '185', name: 'Big Vectors', voices: 4},
	{number: '186', name: 'Poly Swell', voices: 2},
	{number: '187', name: 'Alchemy', voices: 3},
	{number: '188', name: 'Soli-na', voices: 2},
	{number: '189', name: '90s Str Mach', voices: 4},
	{number: '190', name: 'Ultra Cheez', voices: 2},
	{number: '191', name: 'Juno-60 Pad', voices: 3},
	{number: '192', name: 'Progressive', voices: 2},
	{number: '193', name: 'Build-Up Syn', voices: 3},
	{number: '194', name: 'Atlantis 2', voices: 4},
	{number: '195', name: 'Perelandra', voices: 4},
	{number: '196', name: 'Plutonium', voices: 4},
	{number: '197', name: 'Nautilus', voices: 2},
	{number: '198', name: 'Metal Dreams', voices: 2},
	{number: '199', name: 'Glass Clouds', voices: 4},
	{number: '200', name: 'Harmonicloud', voices: 4},
	{number: '201', name: 'Shining Veil', voices: 3},
	{number: '202', name: 'Ethereal JX', voices: 2},
	{number: '203', name: 'Striking 5th', voices: 4},
	{number: '204', name: 'Meow 5ths', voices: 2},
	{number: '205', name: 'Stepflanger', voices: 3},
	{number: '206', name: 'Happy LFOs', voices: 4},
	{number: '207', name: 'Aero Insect', voices: 3},
	{number: '208', name: 'Beat Sweeper', voices: 2},
	{number: '209', name: 'Wormy Lead', voices: 3},
	{number: '210', name: 'Atmo Lead', voices: 3},
	{number: '211', name: 'Caliolead', voices: 3},
	{number: '212', name: 'Tweedles', voices: 2},
	{number: '213', name: 'Raw PWM', voices: 2},
	{number: '214', name: 'Voc Solo 5th', voices: 4},
	{number: '215', name: 'Dirty Lead', voices: 2},
	{number: '216', name: 'Boostweeper1', voices: 2},
	{number: '217', name: 'Boostweeper2', voices: 2},
	{number: '218', name: 'B3 Filth', voices: 4},
	{number: '219', name: 'Phazed Organ', voices: 3},
	{number: '220', name: 'VSw Vibrafon', voices: 3},
	{number: '221', name: 'SA Vibe', voices: 1},
	{number: '222', name: 'Rich Vibes', voices: 2},
	{number: '223', name: 'SpaceGamelan', voices: 4},
	{number: '224', name: 'Toy Vibe', voices: 3},
	{number: '225', name: 'Analog Bomb', voices: 2},
	{number: '226', name: 'Seashore 2', voices: 4},
	{number: '227', name: 'Creation', voices: 4},
	{number: '228', name: 'Cyberjunkie', voices: 4},
	{number: '229', name: 'Sci-Fi Bells', voices: 3},
	{number: '230', name: 'Shine on', voices: 1},
	{number: '231', name: 'DEMO Piano1', voices: 4},
	{number: '232', name: 'DEMO Piano2', voices: 4},
	{number: '233', name: 'DEMO PnoVox', voices: 3},
	{number: '234', name: 'DEMO Str 1', voices: 2},
	{number: '235', name: 'DEMO Str 2', voices: 2},
	{number: '236', name: 'DEMO Str 3', voices: 2},
	{number: '237', name: 'DEMO SynPuls', voices: 2},
	{number: '238', name: 'DEMO 5thPad', voices: 4},
	{number: '239', name: 'DEMO Choir', voices: 2},
	{number: '240', name: 'DEMO Brass', voices: 1},
	{number: '241', name: 'DEMO Tenor', voices: 3},
	{number: '242', name: 'DEMO Tpt', voices: 1},
	{number: '243', name: 'DEMO Flute', voices: 2},
	{number: '244', name: 'DEMO Nylon', voices: 4},
	{number: '245', name: 'DEMO PhaseGt', voices: 4},
	{number: '246', name: 'DEMO DistGt1', voices: 4},
	{number: '247', name: 'DEMO DistGt2', voices: 3},
	{number: '248', name: 'DEMO Strat', voices: 3},
	{number: '249', name: 'DEMO SlapBs', voices: 2},
	{number: '250', name: 'DEMO P.Bass', voices: 1},
	{number: '251', name: 'DEMO SynBs', voices: 2},
	{number: '252', name: 'DEMO SynLead', voices: 4},
	{number: '253', name: 'DEMO Insect', voices: 4},
	{number: '254', name: 'DEMO Buzzzzz', voices: 2},
	{number: '255', name: 'DEMO Crowd', voices: 4}
];

jvtool.banks = {
	"User":          {msb: 80, lsb: 0, patches: jvtool.userPatches},
	"Preset A":      {msb: 81, lsb: 0, patches: jvtool.presetAPatches},
	"Preset B":      {msb: 81, lsb: 1, patches: jvtool.presetBPatches},
	"Preset C":      {msb: 81, lsb: 2, patches: jvtool.presetCPatches},
	"Preset D (GM)": {msb: 81, lsb: 3, patches: jvtool.presetDPatches},
	"Preset E":      {msb: 81, lsb: 4, patches: jvtool.presetEPatches},
	"Session":       {msb: 84, lsb: 0, patches: jvtool.sessionPatches}
};
